[package]
name = "pscontroller-rs"
version = "0.7.0"
authors = ["Edwin Amsler"]
edition = "2018"

categories = ["embedded", "hardware-support", "no-std"]
description = "A hardware-level platform agnostic driver for PlayStation 1 or 2 contoller peripherals. Requires soldering. 😁"
keywords = ["embedded-hal-driver", "playstation", "gamepad"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/RandomInsano/pscontroller-rs"

exclude = [
    "research/*",
]

[features]
default = ["embedded-hal-02"]
embedded-hal-02 = ["dep:embedded-hal-02"]
embedded-hal-1 = ["dep:embedded-hal-1"]

[dependencies]
embedded-hal-02 = { package = "embedded-hal", version = "0.2.6", features = ["unproven"], optional = true }
embedded-hal-1 = { package = "embedded-hal", version = "1.0", optional = true }
bit_reverse = { version = "0.1.7", default-features = false }
bitflags = "1.0"
byteorder = { version = "1.2", default-features = false }

[dev-dependencies]
linux-embedded-hal = "0.2.2"
